config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "tasks", to: "tasks#index", as: "tasks"

  get "tasks/new", to: "tasks#new", as: "new_task"

  post "tasks", to: "tasks#create"

  get "tasks/:id", to: "tasks#show", as: "task"

  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task

  patch "tasks/:id", to: "tasks#update"

  delete "tasks/:id", to: "tasks#destroy", as: :delete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to @task
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to @task
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, notice: "That was successfully deleted."
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.check_box :completed %>
  <%= f.label :completed %>

  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container mt-4">
  <div class="card shadow-lg p-4">
    <h1 class="text-success"> <i class="fa-solid fa-pen-to-square"></i> Edit your task</h1>

    <%= render "form"%>
  </div>

</div>

app/views/tasks/index.html.erb
<div class="container mt-4">
  <h1 class="mb-4">📝 My Tasks for the Day</h1>

  <div class="list-group">
    <% @tasks.each do |task| %>
      <div class="list-group-item d-flex justify-content-between align-items-center">
        <div>
          <input type="checkbox"  <%= "checked" if task.completed %> class="form-check-input me-2">
          <%= link_to task.title, task_path(task), class: "text-decoration-none fw-bold" %>
        </div>
        <div>
          <%= link_to delete_task_path(task), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-outline-danger" do %>
        <i class="fa-solid fa-trash"></i> Delete
      <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="mt-4">
    <%= link_to "+ Add a new task", new_task_path, class: "btn btn-success" %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container mt-5">
  <div class="card shadow-lg p-4">
    <h2 class="text-secondary"> <i class="fa-solid fa-list-check"></i> New task</h2>

    <%= render "form" %>

    <div class="mt-4">
      <%= link_to tasks_path,  class: "btn btn-primary" do%>
    <i class="fa-solid fa-arrow-left"></i>
        Back to Home Page
  <% end %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h2> Details about:
    <%= @task.title %>
  </h2>

  <p><%= @task.details %></p>

  <p>
    <input type="checkbox"  <% if @task.completed %>checked="checked"<% end %>>
    <% if @task.completed %>
      ✅ Task is completed
    <% else %>
      ❌ Task is not completed
    <% end %>
  </p>
  <%= link_to "Edit", edit_task_path(@task), class: "btn btn-light"%>
  <%= link_to "← Back to tasks", tasks_path, class: "btn btn-secondary mt-3" %>
</div>